export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {},
    colors: {
      btnRed: '#F96060',
      signUpGray: '#9B9B9B',
      signUpWhite: '#FFFFFF',
      inputGray: '#EDEDED',
      homeLineBlack: '#313131',
      workMenuDarkBlue: '#292E4E',
      textGray: '#9A9A9A',
      textMenuGray: '#8E8E93',
      todoBlue: '#6074F9',
      shadowGray: '#E0E0E080',
      lightGray: '#E4E4E4',
      statictikGray: '#E8E8E8',
      backColorMenu: '#FDFDFD',
      projectRed: '#E42B6A',
      projectGreen: '#5ABB56',
      projectPurple: '#BC79C3',
      sliderPurple: '#8560F9',
      ChooseColor4: '#3D3A62',
      ChooseColor5: '#F4CA8F',
      veryLightGray: '#F4F4F4',
      descriptionGray: '#9E9E9E',
      borderGray: '#EAEAEA',
      notVeryLightGray: '#F8F8F8',
      buttonGray: '#CCCCCC',
    },
    fontFamily: {
      main: ['Roboto'],
    },
  },
  plugins: [],
};
